---
# tasks file for ansible-oraclercu

- name: Assert RCU mode is supported
  tags: oracle-rcu
  assert:
    that:
      - oracle_rcu_mode in ['create', 'drop', 'forcedrop']
    msg: "oracle_rcu_mode must be either 'create' or 'drop'"

- name: Install required packages
  tags: oracle-rcu
  include_role:
    name: packages
  vars:
    packages_add:
      - unzip

- name: Copy Oracle RCU distribution to target host
  tags: oracle-rcu
  include: "../silpion.lib/tasks/copy.yml"
  vars:
    filename: "{{ oracle_rcu_archive }}"

- name: Create temporary directory for installation files
  tags: oracle-rcu
  file:
    path: "{{ oracle_rcu_tmp }}"
    state: directory
    owner: "{{ oracle_rcu_user }}"
    group: "{{ oracle_rcu_group }}"
    mode: 0755

- name: Extract Oracle RCU installation files
  tags: oracle-rcu
  become_user: "{{ oracle_rcu_user }}"
  become: true
  unarchive:
    src: "{{ lib_persistent_data_path_remote }}/{{ oracle_rcu_archive }}"
    dest: "{{ oracle_rcu_tmp }}"
    remote_src: true
    owner: "{{ oracle_rcu_user }}"
    group: "{{ oracle_rcu_group }}"
    creates: "{{ oracle_rcu_tmp }}/rcuHome"

- include: rcu-run.yml
  tags: oracle-rcu
  become_user: "{{ oracle_rcu_user }}"
  become: true
  when: oracle_rcu_components is defined

- name: Include local facts tasks
  tags: oraclercu
  when: _oracle_rcu_result is defined and oracle_rcu_mode == 'create'
  include: "{{ role_path }}/../silpion.lib/tasks/localfacts.yml"
  vars:
    namespace: oraclercu

# FIXME: Need to fix silpion.lib
- name: Remove local facts
  tags: oraclercu
  when: oracle_rcu_mode in [ 'drop', 'forcedrop' ]
  file:
    path: /etc/ansible/facts.d/oraclercu.fact
    state: absent

- name: Re-read local facts
  when: oracle_rcu_mode in [ 'drop', 'forcedrop' ]
  setup:
    filter: ansible_local
    fact_path: /etc/ansible/facts.d'
